### PR TITLE
Fix CockroachDB dashboard bugs

### PR DESCRIPTION
**Pull request by timaa2k**
Effort together with @ahairape 
- Replace CockroachLabs aggregated queries with on-the-fly Grafana calculated ones for all percentile graphs (Empty before due to missing CockroachDB specific Prometheus rules) [DCOS-51640](https://jira.mesosphere.com/browse/DCOS-51640)
- Fix storage graphs to show the actually used storage capacity [DCOS-47988](https://jira.mesosphere.com/browse/DCOS-47988)
- [Bugfix] Always display missing data as null

### CODE REVIEW

**Comment by jongiddy** [comment]
Looks good to me. Is it possible to put a description in the right-hand column when it has a table?
e.g.: Can we add some text to the bottom like the remainder of this comment, even if it needs scrolling to make visible?


Screenshot from 2019-04-16 14-30-02
The number of disk reads required per query.

**Comment by timaa2k** [comment]
One can add an info test to be displayed when hovered over.

**Comment by timaa2k** [comment]
I've added your comment as an info box on the table @jongiddy

**Comment by timaa2k** [comment]
Please check the box if you're happy @jongiddy

**Review by jieyu — APPROVED** [review]
this lgtm

**Review by jongiddy — APPROVED** [review]

**Review by jgehrcke — APPROVED** [review]

**Pull request merged**
