### PR TITLE
DCOS_OSS-4962 [dcos-diagnostics] Create Grafana Dashboards

### PR DESCRIPTION
**Pull request by makkes**
Add initial dashboard for dcos-diagnostics

https://jira.mesosphere.com/browse/DCOS_OSS-4962

### CODE REVIEW

**Comment by makkes** [comment]
@janisz Would you take a look at this, pls?

**Review by janisz — APPROVED** [review]

**Comment by makkes** [comment]
This is how the dashboard will look like:
Screenshot 2019-03-14 at 16 49 11

**Comment by masonse** [comment]
@makkes please add a panel that shows a bar graph of the collection time of the past diagnostic bundle collections.  Can you overlay the average bundle time as a line over the bar graph?

**Comment by makkes** [comment]
diagnostics-dashboard

**Comment by masonse** [comment]
Looks great.

**Comment by janisz** [comment]
@branden @gracedo @philipnrmn Can you take a look at this?

**Comment by jieyu** [comment]
Please make sure to "export" the json (there's a check mark in Grafana UI) so that "source" is not hard coded to "prometheus"

**Comment by makkes** [comment]
> Please make sure to "export" the json (there's a check mark in Grafana UI) so that "source" is not hard coded to "prometheus"

done. @branden @gracedo @philipnrmn please review

**Review by gracedo — APPROVED** [review]

**Pull request merged**
