### PR TITLE
Adjust metrics naming to match the metric names in Edge-LB [1.13.x]

### PR DESCRIPTION
**Pull request by vespian**
See the discussion in https://github.com/mesosphere/dcos-edge-lb/pull/473#discussion_r313741916

### CODE REVIEW

**Comment by vespian** [comment]
@gracedo @branden @philipnrmn PTAL

**Review by philipnrmn — APPROVED** [review]

**Comment by philipnrmn** [comment]
Hi @vespian, thanks for the PR. Are we sure this will work for users with earlier versions of 1.13?

**Comment by vespian** [comment]
> Hi @vespian, thanks for the PR. Are we sure this will work for users with earlier versions of 1.13?

@philipnrmn Edge-LB with the metrics being renamed included was not released yet, and AFAIK neither was dcos-monitoring package so we should be good here.

**Comment by gracedo** [comment]
@vespian Does there need to be some coordination between edge-LB and dcos-monitoring releases?

**Comment by vespian** [comment]
@gracedo I would say that we need to release Edge-LB after we release next dcos-monitoring package so that when we announce that we have metrics in Edge-lB in release X.y.z, there are already dashboards available for it. 

CC: @GoelDeepak

**Comment by gracedo** [comment]
@vespian Is there a timeline for when we need to release dcos-monitoring so it doesn't block Edge-LB?

**Comment by vespian** [comment]
@gracedo There is none. When would you like to release dcos-monitoring? How often do you make dcos-monitoring releases?

**Comment by gracedo** [comment]
We generally will cut a release when we have a feature or major bug fix. I will probably be cutting a release end of this week/next week since we do have a feature inflight. I'll go ahead and merge your changes in and ping you when the release is out :)

**Pull request merged**
