### PR TITLE
Cassandra dashboard

### PR DESCRIPTION
**Pull request by viivek46**
Adds dashboard for monitoring DC/OS Cassandra.

JIRA Issue: https://jira.mesosphere.com/browse/DCOS-52831

Live Dashboard:
DCOS 1.13 :https://soak113s.testing.mesosphe.re/service/monitoring/grafana/d/000000086/cassandra-cluster-summary?refresh=30s&orgId=1

### CODE REVIEW

**Comment by gracedo** [comment]
Can you move the 1.12 dashboard to the [1.12.x branch](https://github.com/dcos/grafana-dashboards/tree/1.12.x)?

**Review by branden — CHANGES_REQUESTED** [review]
+1 @gracedo https://github.com/dcos/grafana-dashboards/pull/63#issuecomment-499954763

**Comment by viivek46** [comment]
@branden @gracedo updated this PR and removed Cassandra dcos 1.12 dashboard from this PR.

**Review by gracedo — APPROVED** [review]
LGTM - can you open up a PR for the 1.12.x branch dashboard as well? We're planning on releasing the next version of dcos-monitoring by Wednesday and I'd love to get the 1.12.x dashboard pulled in by then as well :) thanks!

**Comment by viivek46** [comment]
@gracedo here it is : 
https://github.com/dcos/grafana-dashboards/pull/64
please approve it as well.

**Pull request merged**
